AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function. 
Resources:
  rMemeGenerator: # Lambda Function & API Gateway Event
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 10
      Policies:
        - S3CrudPolicy:
            BucketName: !GetAtt rImageBucket.Arn
      Events:
        Api: 
          Type: Api
          Properties:
            Path: /meme
            Method: POST
  rImageBucket:
    Type: AWS::S3::Bucket

Globals:
  Api:
    BinaryMediaTypes:
      # These are equivalent to image/png when deployed
      - image~1png
